
/* ------------------------- usrinc/tip.h --------------------- */
/*                                                              */
/*              Copyright (c) 2000 - 2002 Tmax Soft Co., Ltd    */
/*                   All Rights Reserved                        */
/*                                                              */
/* ------------------------------------------------------------ */

#ifndef _TMAX_TIP_H
#define _TMAX_TIP_H

#include <usrinc/tmadmin.h>

/*
 * TIP error messages: TIP_ERROR field
 */

#define TIPNOERR        0
#define TIPEBADFLD      1       /* bad field key */
#define TIPEIMPL        2       /* unimplemented request */
#define TIPEAUTH        3       /* authrization check fail */
#define TIPEOS          4       /* OS errors such as malloc fail */
#define TIPENOENT       5       /* no entry found */
#define TIPESVCFAIL     6       /* Admin SVC fail */

#define TIP_AFLAG       TMADM_AFLAG     /* ALL */
#define TIP_CFLAG       TMADM_CFLAG     /* CLH or Client */
#define TIP_FFLAG       TMADM_FFLAG     /* Force */
#define TIP_GFLAG       TMADM_GFLAG     /* SVG or Gateway */
#define TIP_IFLAG       TMADM_IFLAG     /* Immediate or Idle */
#define TIP_NFLAG       TMADM_NFLAG     /* Not Ready or Node or Number */
#define TIP_PFLAG       TMADM_PFLAG     /* Server Process */
#define TIP_RFLAG       TMADM_RFLAG     /* RQ */
#define TIP_SFLAG       TMADM_SFLAG     /* SVR or SVC */
#define TIP_TFLAG       TMADM_TFLAG     /* TMS */
#define TIP_VFLAG       TMADM_VFLAG     /* SVR */
#define TIP_EFLAG	TMADM_EFLAG	/* TMM (else engine flags) */

#define TIP_TMM		TMADM_TMM       /* TMM */
#define TIP_CLH		TMADM_CLH       /* CLH */
#define TIP_TMS		TMADM_TMS       /* TMS */
#define TIP_SVR 	TMADM_SVR       /* SVR */

/*
 * TMAX FDL header file. automatically generated by fdlc
 */



#define TIP_OPERATION 	 ((FLDKEY)485762049) /* number: 16000001 type: string */ 
#define TIP_SEGMENT 	 ((FLDKEY)485762050) /* number: 16000002 type: string */ 
#define TIP_SECTION 	 ((FLDKEY)485762051) /* number: 16000003 type: string */ 
#define TIP_NODE 	 ((FLDKEY)485762052) /* number: 16000004 type: string */ 
#define TIP_OCCURS 	 ((FLDKEY)217326597) /* number: 16000005 type: int */ 
#define TIP_FLAGS 	 ((FLDKEY)217326598) /* number: 16000006 type: int */ 
#define TIP_CURSOR 	 ((FLDKEY)485762055) /* number: 16000007 type: string */ 
#define TIP_SESTM 	 ((FLDKEY)217326600) /* number: 16000008 type: int */ 
#define TIP_ERROR 	 ((FLDKEY)217326601) /* number: 16000009 type: int */ 
#define TIP_STATE 	 ((FLDKEY)217326602) /* number: 16000010 type: int */ 
#define TIP_MORE 	 ((FLDKEY)217326603) /* number: 16000011 type: int */ 
#define TIP_BADFIELD 	 ((FLDKEY)485762060) /* number: 16000012 type: string */ 
#define TIP_CMD 	 ((FLDKEY)485762061) /* number: 16000013 type: string */ 
#define TIP_CLID 	 ((FLDKEY)217326606) /* number: 16000014 type: int */ 
#define TIP_MSG 	 ((FLDKEY)485762063) /* number: 16000015 type: string */ 
#define TIP_NAME 	 ((FLDKEY)485762148) /* number: 16000100 type: string */ 
#define TIP_SHMKEY 	 ((FLDKEY)217326693) /* number: 16000101 type: int */ 
#define TIP_MINCLH 	 ((FLDKEY)217326694) /* number: 16000102 type: int */ 
#define TIP_MAXCLH 	 ((FLDKEY)217326695) /* number: 16000103 type: int */ 
#define TIP_MAXUSER 	 ((FLDKEY)217326696) /* number: 16000104 type: int */ 
#define TIP_TPORTNO 	 ((FLDKEY)217326697) /* number: 16000105 type: int */ 
#define TIP_RACPORT 	 ((FLDKEY)217326698) /* number: 16000106 type: int */ 
#define TIP_MAXSACALL 	 ((FLDKEY)217326699) /* number: 16000107 type: int */ 
#define TIP_MAXCACALL 	 ((FLDKEY)217326700) /* number: 16000108 type: int */ 
#define TIP_MAXCONV_NODE 	 ((FLDKEY)217326701) /* number: 16000109 type: int */ 
#define TIP_MAXCONV_SERVER 	 ((FLDKEY)217326702) /* number: 16000110 type: int */ 
#define TIP_CMTRET 	 ((FLDKEY)217326703) /* number: 16000111 type: int */ 
#define TIP_BLOCKTIME 	 ((FLDKEY)217326704) /* number: 16000112 type: int */ 
#define TIP_TXTIME 	 ((FLDKEY)217326705) /* number: 16000113 type: int */ 
#define TIP_IDLETIME 	 ((FLDKEY)217326706) /* number: 16000114 type: int */ 
#define TIP_CLICHKINT 	 ((FLDKEY)217326707) /* number: 16000115 type: int */ 
#define TIP_NLIVEINQ 	 ((FLDKEY)217326708) /* number: 16000116 type: int */ 
#define TIP_SECURITY 	 ((FLDKEY)485762165) /* number: 16000117 type: string */ 
#define TIP_OWNER 	 ((FLDKEY)485762166) /* number: 16000118 type: string */ 
#define TIP_CPC 	 ((FLDKEY)217326711) /* number: 16000119 type: int */ 
#define TIP_NCLHCHKTIME 	 ((FLDKEY)217326714) /* number: 16000122 type: int */ 
#define TIP_DOMAINID 	 ((FLDKEY)217326715) /* number: 16000123 type: int */ 
#define TIP_IPCPERM 	 ((FLDKEY)217326716) /* number: 16000124 type: int */ 
#define TIP_MAXNODE 	 ((FLDKEY)217326717) /* number: 16000125 type: int */ 
#define TIP_MAXSVG 	 ((FLDKEY)217326718) /* number: 16000126 type: int */ 
#define TIP_MAXSVR 	 ((FLDKEY)217326719) /* number: 16000127 type: int */ 
#define TIP_MAXSVC 	 ((FLDKEY)217326720) /* number: 16000128 type: int */ 
#define TIP_MAXSPR 	 ((FLDKEY)217326721) /* number: 16000129 type: int */ 
#define TIP_MAXTMS 	 ((FLDKEY)217326722) /* number: 16000130 type: int */ 
#define TIP_MAXCPC 	 ((FLDKEY)217326723) /* number: 16000131 type: int */ 
#define TIP_MAXROUT 	 ((FLDKEY)217326724) /* number: 16000132 type: int */ 
#define TIP_MAXROUTSVG 	 ((FLDKEY)217326725) /* number: 16000133 type: int */ 
#define TIP_MAXRQ 	 ((FLDKEY)217326726) /* number: 16000134 type: int */ 
#define TIP_MAXGW 	 ((FLDKEY)217326727) /* number: 16000135 type: int */ 
#define TIP_MAXCOUSIN 	 ((FLDKEY)217326728) /* number: 16000136 type: int */ 
#define TIP_MAXCOUSINSVG 	 ((FLDKEY)217326729) /* number: 16000137 type: int */ 
#define TIP_MAXBACKUP 	 ((FLDKEY)217326730) /* number: 16000138 type: int */ 
#define TIP_MAXBACKUPSVG 	 ((FLDKEY)217326731) /* number: 16000139 type: int */ 
#define TIP_MAXTOTALSVG 	 ((FLDKEY)217326732) /* number: 16000140 type: int */ 
#define TIP_MAXPROD 	 ((FLDKEY)217326733) /* number: 16000141 type: int */ 
#define TIP_MAXFUNC 	 ((FLDKEY)217326734) /* number: 16000142 type: int */ 
#define TIP_TXPENDINGTIME 	 ((FLDKEY)217326735) /* number: 16000143 type: int */ 
#define TIP_NO 	 ((FLDKEY)217326736) /* number: 16000144 type: int */ 
#define TIP_TIPSVC 	 ((FLDKEY)485762193) /* number: 16000145 type: string */ 
#define TIP_NODECOUNT 	 ((FLDKEY)217326738) /* number: 16000146 type: int */ 
#define TIP_SVGCOUNT 	 ((FLDKEY)217326739) /* number: 16000147 type: int */ 
#define TIP_SVRCOUNT 	 ((FLDKEY)217326740) /* number: 16000148 type: int */ 
#define TIP_SVCCOUNT 	 ((FLDKEY)217326741) /* number: 16000149 type: int */ 
#define TIP_COUSIN_COUNT 	 ((FLDKEY)217326742) /* number: 16000150 type: int */ 
#define TIP_BACKUP_COUNT 	 ((FLDKEY)217326743) /* number: 16000151 type: int */ 
#define TIP_ROUT_COUNT 	 ((FLDKEY)217326744) /* number: 16000152 type: int */ 
#define TIP_STYPE 	 ((FLDKEY)485762201) /* number: 16000153 type: string */ 
#define TIP_VERSION 	 ((FLDKEY)485762202) /* number: 16000154 type: string */ 
#define TIP_EXPDATE 	 ((FLDKEY)485762203) /* number: 16000155 type: string */ 
#define TIP_DOMAINCOUNT 	 ((FLDKEY)217326748) /* number: 16000156 type: int */ 
#define TIP_RSVG_GCOUNT 	 ((FLDKEY)217326749) /* number: 16000157 type: int */ 
#define TIP_RSVG_COUNT 	 ((FLDKEY)217326750) /* number: 16000158 type: int */ 
#define TIP_CSVG_GCOUNT 	 ((FLDKEY)217326751) /* number: 16000159 type: int */ 
#define TIP_CSVG_COUNT 	 ((FLDKEY)217326752) /* number: 16000160 type: int */ 
#define TIP_BSVG_GCOUNT 	 ((FLDKEY)217326753) /* number: 16000161 type: int */ 
#define TIP_BSVG_COUNT 	 ((FLDKEY)217326754) /* number: 16000162 type: int */ 
#define TIP_PROD_COUNT 	 ((FLDKEY)217326755) /* number: 16000163 type: int */ 
#define TIP_FUNC_COUNT 	 ((FLDKEY)217326756) /* number: 16000164 type: int */ 
#define TIP_SHMSIZE 	 ((FLDKEY)217326757) /* number: 16000165 type: int */ 
#define TIP_CRYPT 	 ((FLDKEY)485762214) /* number: 16000166 type: string */ 
#define TIP_DOMAIN_TMMLOGLVL 	 ((FLDKEY)485762215) /* number: 16000167 type: string */ 
#define TIP_DOMAIN_CLHLOGLVL 	 ((FLDKEY)485762216) /* number: 16000168 type: string */ 
#define TIP_DOMAIN_TMSLOGLVL 	 ((FLDKEY)485762217) /* number: 16000169 type: string */ 
#define TIP_DOMAIN_LOGLVL 	 ((FLDKEY)485762218) /* number: 16000170 type: string */ 
#define TIP_DOMAIN_MAXTHREAD 	 ((FLDKEY)217326763) /* number: 16000171 type: int */ 
#define TIP_DOMAINNAME 	 ((FLDKEY)485762249) /* number: 16000201 type: string */ 
#define TIP_CLHQTIMEOUT 	 ((FLDKEY)217326797) /* number: 16000205 type: int */ 
#define TIP_CMPRPORT 	 ((FLDKEY)485762263) /* number: 16000215 type: string */ 
#define TIP_CMPRSIZE 	 ((FLDKEY)217326808) /* number: 16000216 type: int */ 
#define TIP_TMAXDIR 	 ((FLDKEY)485762266) /* number: 16000218 type: string */ 
#define TIP_TMAXHOME 	 ((FLDKEY)485762267) /* number: 16000219 type: string */ 
#define TIP_APPDIR 	 ((FLDKEY)485762268) /* number: 16000220 type: string */ 
#define TIP_PATHDIR 	 ((FLDKEY)485762269) /* number: 16000221 type: string */ 
#define TIP_TLOGDIR 	 ((FLDKEY)485762270) /* number: 16000222 type: string */ 
#define TIP_SLOGDIR 	 ((FLDKEY)485762271) /* number: 16000223 type: string */ 
#define TIP_ULOGDIR 	 ((FLDKEY)485762272) /* number: 16000224 type: string */ 
#define TIP_ENVFILE 	 ((FLDKEY)485762273) /* number: 16000225 type: string */ 
#define TIP_IP 	 ((FLDKEY)485762276) /* number: 16000228 type: string */ 
#define TIP_TMMOPT 	 ((FLDKEY)485762278) /* number: 16000230 type: string */ 
#define TIP_CLHOPT 	 ((FLDKEY)485762279) /* number: 16000231 type: string */ 
#define TIP_MAXGWSVR 	 ((FLDKEY)217326830) /* number: 16000238 type: int */ 
#define TIP_MAXRQSVR 	 ((FLDKEY)217326831) /* number: 16000239 type: int */ 
#define TIP_MAXGWCPC 	 ((FLDKEY)217326832) /* number: 16000240 type: int */ 
#define TIP_MAXRQCPC 	 ((FLDKEY)217326833) /* number: 16000241 type: int */ 
#define TIP_CPORTNO 	 ((FLDKEY)217326834) /* number: 16000242 type: int */ 
#define TIP_REALSVR 	 ((FLDKEY)485762291) /* number: 16000243 type: string */ 
#define TIP_RSCPC 	 ((FLDKEY)217326836) /* number: 16000244 type: int */ 
#define TIP_AUTOBACKUP 	 ((FLDKEY)217326837) /* number: 16000245 type: int */ 
#define TIP_HOSTNAME 	 ((FLDKEY)485762294) /* number: 16000246 type: string */ 
#define TIP_NODETYPE 	 ((FLDKEY)217326839) /* number: 16000247 type: int */ 
#define TIP_CPU 	 ((FLDKEY)217326840) /* number: 16000248 type: int */ 
#define TIP_CURCLH 	 ((FLDKEY)217326841) /* number: 16000249 type: int */ 
#define TIP_LIVECTIME 	 ((FLDKEY)485762298) /* number: 16000250 type: string */ 
#define TIP_NODE_TMMLOGLVL 	 ((FLDKEY)485762299) /* number: 16000251 type: string */ 
#define TIP_NODE_CLHLOGLVL 	 ((FLDKEY)485762300) /* number: 16000252 type: string */ 
#define TIP_NODE_TMSLOGLVL 	 ((FLDKEY)485762301) /* number: 16000253 type: string */ 
#define TIP_NODE_LOGLVL 	 ((FLDKEY)485762302) /* number: 16000254 type: string */ 
#define TIP_NODE_MAXTHREAD 	 ((FLDKEY)217326847) /* number: 16000255 type: int */ 
#define TIP_EXTPORT 	 ((FLDKEY)217326848) /* number: 16000256 type: int */ 
#define TIP_EXTCLHPORT 	 ((FLDKEY)217326849) /* number: 16000257 type: int */ 
#define TIP_SVGTYPE 	 ((FLDKEY)485762350) /* number: 16000302 type: string */ 
#define TIP_COUSIN 	 ((FLDKEY)485762352) /* number: 16000304 type: string */ 
#define TIP_BACKUP 	 ((FLDKEY)485762353) /* number: 16000305 type: string */ 
#define TIP_LOAD 	 ((FLDKEY)217326898) /* number: 16000306 type: int */ 
#define TIP_DBNAME 	 ((FLDKEY)485762357) /* number: 16000309 type: string */ 
#define TIP_OPENINFO 	 ((FLDKEY)485762358) /* number: 16000310 type: string */ 
#define TIP_CLOSEINFO 	 ((FLDKEY)485762359) /* number: 16000311 type: string */ 
#define TIP_MINTMS 	 ((FLDKEY)217326904) /* number: 16000312 type: int */ 
#define TIP_TMSNAME 	 ((FLDKEY)485762362) /* number: 16000314 type: string */ 
#define TIP_XAOPTION 	 ((FLDKEY)485762367) /* number: 16000319 type: string */ 
#define TIP_SVG_TMSTYPE 	 ((FLDKEY)485762368) /* number: 16000320 type: string */ 
#define TIP_SVG_TMSOPT 	 ((FLDKEY)485762369) /* number: 16000321 type: string */ 
#define TIP_SVG_TMSTHREADS 	 ((FLDKEY)217326914) /* number: 16000322 type: int */ 
#define TIP_SVG_TMSLOGLVL 	 ((FLDKEY)485762371) /* number: 16000323 type: string */ 
#define TIP_SVG_LOGLVL 	 ((FLDKEY)485762372) /* number: 16000324 type: string */ 
#define TIP_NODENAME     ((FLDKEY)485762373) /* number: 16000325 type: string */
#define TIP_SVGNAME 	 ((FLDKEY)485762399) /* number: 16000351 type: string */ 
#define TIP_CLOPT 	 ((FLDKEY)485762401) /* number: 16000353 type: string */ 
#define TIP_SEQ 	 ((FLDKEY)217326946) /* number: 16000354 type: int */ 
#define TIP_MIN 	 ((FLDKEY)217326947) /* number: 16000355 type: int */ 
#define TIP_MAX 	 ((FLDKEY)217326948) /* number: 16000356 type: int */ 
#define TIP_CONV 	 ((FLDKEY)217326950) /* number: 16000358 type: int */ 
#define TIP_MAXQCOUNT 	 ((FLDKEY)217326951) /* number: 16000359 type: int */ 
#define TIP_ASQCOUNT 	 ((FLDKEY)217326952) /* number: 16000360 type: int */ 
#define TIP_MAXRSTART 	 ((FLDKEY)217326953) /* number: 16000361 type: int */ 
#define TIP_GPERIOD 	 ((FLDKEY)217326954) /* number: 16000362 type: int */ 
#define TIP_RESTART 	 ((FLDKEY)217326955) /* number: 16000363 type: int */ 
#define TIP_SVRTYPE 	 ((FLDKEY)485762412) /* number: 16000364 type: string */ 
#define TIP_SCHEDULE 	 ((FLDKEY)217326958) /* number: 16000366 type: int */ 
#define TIP_TARGET 	 ((FLDKEY)485762417) /* number: 16000369 type: string */ 
#define TIP_DEPEND 	 ((FLDKEY)485762418) /* number: 16000370 type: string */ 
#define TIP_CASCADE 	 ((FLDKEY)217326963) /* number: 16000371 type: int */ 
#define TIP_PROCNAME 	 ((FLDKEY)485762420) /* number: 16000372 type: string */ 
#define TIP_LIFESPAN 	 ((FLDKEY)485762421) /* number: 16000373 type: string */ 
#define TIP_DDRI 	 ((FLDKEY)485762422) /* number: 16000374 type: string */ 
#define TIP_CURSVR 	 ((FLDKEY)217326967) /* number: 16000375 type: int */ 
#define TIP_SVGNO 	 ((FLDKEY)217326968) /* number: 16000376 type: int */ 
#define TIP_SVR_LOGLVL 	 ((FLDKEY)485762425) /* number: 16000377 type: string */ 
#define TIP_SVRNAME 	 ((FLDKEY)485762449) /* number: 16000401 type: string */ 
#define TIP_PRI 	 ((FLDKEY)217326994) /* number: 16000402 type: int */ 
#define TIP_SVCTIME 	 ((FLDKEY)217326995) /* number: 16000403 type: int */ 
#define TIP_ROUTING 	 ((FLDKEY)485762452) /* number: 16000404 type: string */ 
#define TIP_EXPORT 	 ((FLDKEY)217326997) /* number: 16000405 type: int */ 
#define TIP_AUTOTRAN 	 ((FLDKEY)217326998) /* number: 16000406 type: int */ 
#define TIP_FLDTYPE 	 ((FLDKEY)485762474) /* number: 16000426 type: string */ 
#define TIP_RANGES 	 ((FLDKEY)485762475) /* number: 16000427 type: string */ 
#define TIP_SUBTYPE 	 ((FLDKEY)485762476) /* number: 16000428 type: string */ 
#define TIP_ELEMENT 	 ((FLDKEY)485762477) /* number: 16000429 type: string */ 
#define TIP_BUFTYPE 	 ((FLDKEY)485762478) /* number: 16000430 type: string */ 
#define TIP_OFFSET 	 ((FLDKEY)217327023) /* number: 16000431 type: int */ 
#define TIP_FLDLEN 	 ((FLDKEY)217327024) /* number: 16000432 type: int */ 
#define TIP_PRESVC 	 ((FLDKEY)485762500) /* number: 16000452 type: string */ 
#define TIP_QSIZE 	 ((FLDKEY)217327045) /* number: 16000453 type: int */ 
#define TIP_FILEPATH 	 ((FLDKEY)485762502) /* number: 16000454 type: string */ 
#define TIP_BOOT 	 ((FLDKEY)485762503) /* number: 16000455 type: string */ 
#define TIP_FSYNC 	 ((FLDKEY)217327048) /* number: 16000456 type: int */ 
#define TIP_BUFFERING 	 ((FLDKEY)217327049) /* number: 16000457 type: int */ 
#define TIP_GWTYPE 	 ((FLDKEY)485762549) /* number: 16000501 type: string */ 
#define TIP_PORTNO 	 ((FLDKEY)217327094) /* number: 16000502 type: int */ 
#define TIP_RGWADDR 	 ((FLDKEY)485762552) /* number: 16000504 type: string */ 
#define TIP_RGWPORTNO 	 ((FLDKEY)217327097) /* number: 16000505 type: int */ 
#define TIP_KEY 	 ((FLDKEY)485762556) /* number: 16000508 type: string */ 
#define TIP_BACKUP_RGWADDR 	 ((FLDKEY)485762557) /* number: 16000509 type: string */ 
#define TIP_BACKUP_RGWPORTNO 	 ((FLDKEY)217327102) /* number: 16000510 type: int */ 
#define TIP_TIMEOUT 	 ((FLDKEY)217327103) /* number: 16000511 type: int */ 
#define TIP_DIRECTION 	 ((FLDKEY)485762560) /* number: 16000512 type: string */ 
#define TIP_MAXINRGW 	 ((FLDKEY)217327105) /* number: 16000513 type: int */ 
#define TIP_GWOWNER 	 ((FLDKEY)485762563) /* number: 16000515 type: string */ 
#define TIP_RGWOWNER 	 ((FLDKEY)485762564) /* number: 16000516 type: string */ 
#define TIP_RGWPASSWD 	 ((FLDKEY)485762565) /* number: 16000517 type: string */ 
#define TIP_PTIMEOUT 	 ((FLDKEY)217327110) /* number: 16000518 type: int */ 
#define TIP_PTIMEINT 	 ((FLDKEY)217327111) /* number: 16000519 type: int */ 
#define TIP_FQSTART 	 ((FLDKEY)217327144) /* number: 16000552 type: int */ 
#define TIP_FQEND 	 ((FLDKEY)217327145) /* number: 16000553 type: int */ 
#define TIP_ENTRY 	 ((FLDKEY)485762602) /* number: 16000554 type: string */ 
#define TIP_STATUS 	 ((FLDKEY)485762649) /* number: 16000601 type: string */ 
#define TIP_STIME 	 ((FLDKEY)485762650) /* number: 16000602 type: string */ 
#define TIP_TTIME 	 ((FLDKEY)217327195) /* number: 16000603 type: int */ 
#define TIP_SVC_STIME 	 ((FLDKEY)217327196) /* number: 16000604 type: int */ 
#define TIP_COUNT 	 ((FLDKEY)217327197) /* number: 16000605 type: int */ 
#define TIP_NUM_FREE 	 ((FLDKEY)217327199) /* number: 16000607 type: int */ 
#define TIP_NUM_REPLY 	 ((FLDKEY)217327200) /* number: 16000608 type: int */ 
#define TIP_NUM_FAIL 	 ((FLDKEY)217327201) /* number: 16000609 type: int */ 
#define TIP_NUM_REQ 	 ((FLDKEY)217327202) /* number: 16000610 type: int */ 
#define TIP_ENQ_REQS 	 ((FLDKEY)217327203) /* number: 16000611 type: int */ 
#define TIP_DEQ_REQS 	 ((FLDKEY)217327204) /* number: 16000612 type: int */ 
#define TIP_ENQ_REPLYS 	 ((FLDKEY)217327205) /* number: 16000613 type: int */ 
#define TIP_DEQ_REPLYS 	 ((FLDKEY)217327206) /* number: 16000614 type: int */ 
#define TIP_CLHNO 	 ((FLDKEY)217327207) /* number: 16000615 type: int */ 
#define TIP_SVR_NAME 	 ((FLDKEY)485762664) /* number: 16000616 type: string */ 
#define TIP_SVC_NAME 	 ((FLDKEY)485762665) /* number: 16000617 type: string */ 
#define TIP_AVERAGE 	 ((FLDKEY)351544938) /* number: 16000618 type: float */ 
#define TIP_QCOUNT 	 ((FLDKEY)217327211) /* number: 16000619 type: int */ 
#define TIP_CQCOUNT 	 ((FLDKEY)217327212) /* number: 16000620 type: int */ 
#define TIP_QAVERAGE 	 ((FLDKEY)351544941) /* number: 16000621 type: float */ 
#define TIP_MINTIME 	 ((FLDKEY)351544942) /* number: 16000622 type: float */ 
#define TIP_MAXTIME 	 ((FLDKEY)351544943) /* number: 16000623 type: float */ 
#define TIP_FAIL_COUNT 	 ((FLDKEY)217327216) /* number: 16000624 type: int */ 
#define TIP_ERROR_COUNT 	 ((FLDKEY)217327217) /* number: 16000625 type: int */ 
#define TIP_PID 	 ((FLDKEY)217327218) /* number: 16000626 type: int */ 
#define TIP_TOTAL_COUNT 	 ((FLDKEY)217327219) /* number: 16000627 type: int */ 
#define TIP_TOTAL_SVCFAIL_COUNT 	 ((FLDKEY)217327220) /* number: 16000628 type: int */ 
#define TIP_TOTAL_ERROR_COUNT 	 ((FLDKEY)217327221) /* number: 16000629 type: int */ 
#define TIP_TOTAL_AVG 	 ((FLDKEY)351544950) /* number: 16000630 type: float */ 
#define TIP_TOTAL_RUNNING_COUNT 	 ((FLDKEY)217327223) /* number: 16000631 type: int */ 
#define TIP_TMS_NAME 	 ((FLDKEY)485762680) /* number: 16000632 type: string */ 
#define TIP_SVG_NAME 	 ((FLDKEY)485762681) /* number: 16000633 type: string */ 
#define TIP_SPRI 	 ((FLDKEY)217327226) /* number: 16000634 type: int */ 
#define TIP_TI_THRI 	 ((FLDKEY)217327227) /* number: 16000635 type: int */ 
#define TIP_TI_AVG 	 ((FLDKEY)351544956) /* number: 16000636 type: float */ 
#define TIP_TI_XID 	 ((FLDKEY)485762685) /* number: 16000637 type: string */ 
#define TIP_TI_XA_STATUS 	 ((FLDKEY)485762686) /* number: 16000638 type: string */ 
#define TIP_GW_NAME 	 ((FLDKEY)485762687) /* number: 16000639 type: string */ 
#define TIP_GW_NO 	 ((FLDKEY)217327232) /* number: 16000640 type: int */ 
#define TIP_GW_HOSTN 	 ((FLDKEY)485762689) /* number: 16000641 type: string */ 
#define TIP_GW_CTYPE 	 ((FLDKEY)485762690) /* number: 16000642 type: string */ 
#define TIP_GW_CTYPE2 	 ((FLDKEY)485762691) /* number: 16000643 type: string */ 
#define TIP_GW_IPADDR 	 ((FLDKEY)485762692) /* number: 16000644 type: string */ 
#define TIP_GW_PORT 	 ((FLDKEY)217327237) /* number: 16000645 type: int */ 
#define TIP_GW_STATUS 	 ((FLDKEY)485762694) /* number: 16000646 type: string */ 
#define TIP_IPADDR 	 ((FLDKEY)485762698) /* number: 16000650 type: string */ 
#define TIP_USRNAME 	 ((FLDKEY)485762699) /* number: 16000651 type: string */ 
#define TIP_MODULE       ((FLDKEY)217327244) /* number: 16000652 type: int */ 
#define TIP_LOGLVL       ((FLDKEY)485762701) /* number: 16000653 type: string */ 
#define TIP_SPEC         ((FLDKEY)485762702) /* number: 16000654 type: string */ 
#define TIP_EXTRA_OPTION 	 ((FLDKEY)217327292) /* number: 16000700 type: int */ 
#endif
